### PR TITLE
Added decoration builder

### PR DESCRIPTION
**Pull request by Sourav-Sonkar**
https://github.com/bensonarafat/super_tooltip/issues/107
Decoration need to have access target property,as if we need to pass a custom shape , then we need get access to the target property.

Suggestion to have a call back method which provides target in the supertooltip
```
typedef DecorationBuilder = Decoration Function(
  Offset target,
);
```

### CODE REVIEW

**Comment by bensonarafat** [comment]
Thank @Sourav-Sonkar for your contriubtion
Let me check it out.

**Comment by Sourav-Sonkar** [comment]
@bensonarafat Should i remove the Deprecated tag or remove the decoration parameter to fix the lint??

**Comment by bensonarafat** [comment]
@Sourav-Sonkar 
Can't we keep both? 
And set an assert. So they cant use both as the same time

**Comment by Sourav-Sonkar** [comment]
> @Sourav-Sonkar Can't we keep both? And set an assert. So they cant use both as the same time

@bensonarafat  we can keep both ... but i think it would made more sense it DecorationBuilder only...as both will be returning decoration only

**Comment by Sourav-Sonkar** [comment]
@bensonarafat  removed decoration parameter

**Comment by bensonarafat** [comment]
Great @Sourav-Sonkar 
Could you also add an example readme, on how this can be used?
So, this can help others
thanks

**Comment by Sourav-Sonkar** [comment]
@bensonarafat add documentation please check

**Review by bensonarafat — APPROVED** [review]

**Comment by bensonarafat** [comment]
Great @Sourav-Sonkar 
I will merge it tomorrow. 
thanks

**Pull request merged**
